### ISSUE TITLE
Chart colours and fonts

### ISSUE THREAD

**Issue by kirsten-olson** [rcpch/digital-growth-charts-react-component-library#1]
We plan to have one or more themes for the growth charts. We need to agree the fonts and colours for each.

**Fonts (all chart themes)**
* [ ] Axis text, labels - Arial (to check on sizing)
* [ ] Title/heading - Montserrat (to check on sizing)

**Colours (each chart theme)** - on these elements:
* [ ] Gridlines
* [ ] Axes
* [ ] Axis labels and tick labels
* [ ] Centile lines
* [ ] Background

@eatyourpeas, @Jo-Ball

**Comment by kirsten-olson** [comment]
We agreed at 08/01/21 sprint meeting that @Jo-Ball will recommend about three 'themes' for the charts based on RCPCH brand palette

**Comment by Jo-Ball** [comment]
Here is workboard for RCPCH colour suggestions
[GrowthCharts-RCPCH Colour suggestions Jan 21.pdf](https://github.com/rcpch/digital-growth-charts-react-component-library/files/5855379/GrowthCharts-RCPCH.Colour.suggestions.Jan.21.pdf)

**Comment by pacharanero** [comment]
Nice! Will add these colour options to the theme selector!

**Comment by eatyourpeas** [comment]
@kirsten-olson I have made as many of those changes as I can. It is live [here](https://rcpch-dgc-react-client-unstable.azurewebsites.net/). Let me know if you want to change anything. The fonts are not in yet and I am having some trouble with the tooltip labels aligning.
The best place to post issues is the chart package repository. I will add you and @Jo-Ball.
