### ISSUE TITLE
Linting and formatting

### ISSUE THREAD

**Issue by BrianClevermed** [rcpch/digital-growth-charts-react-component-library#12]
Hi

We have just upgraded to the latest version of the charting library and are having some problems getting the charts to render.

The first issue we have come across is the styling, there appears to be errors in [this file](https://github.com/rcpch/digital-growth-charts-react-component-library/blob/main/src/functions/stylesDefaultValues.ts) 

The code:
`newStyle.height === null && 600`

seems to be trying to set default values but that is not what it is doing, I think the correct code would be something like:

`newStyle.height = newStyle.height == null ? 600 : newStyle.height`

this will set newStyle.height to 600 if the current value is null or undefined (=== will only check for null) this code could also be made a lot more concise using object spread but may be more difficult to understand.

The checks for null such as `if (newStyle.tickLabelTextStyle===null)` will only work if the value is null the typescript does not all null to be set only undefined this could be fixed by adding a check for undefined or changing to == as mentioned above.

=== should be used everywhere except checking for null when you also want to check for undefined.

A linting tool such as eslint with moderately strict settings should catch issues like this as the current code would do nothing.

I would also recommend adding a formatting tool like prettier to help keep code style consistent.

I would be happy to do a PR if you would like me to resolve any of these issues, adding a formatter would change the formatting of all the files so may be difficult to review.

**Comment by eatyourpeas** [comment]
Thanks for this - I am really grateful for the feedback. Looking back over it not sure what I was thinking. I have added prettier and eslint and have refactored the file as you suggest. I looked at using the spreader function as you suggest - would be neater but I opted for readability - I will be fifty this year and so I can remember what I have done I have to leave little clues in the code to decipher later what I have forgotten. Again, very happy to accept advice and corrections.
To my efforts I think it works but I am sure will benefit from improvement and checking. I have altered the months on the x axis also which was wrongly rendering month ticks every 5 weeks.

Do remember that it accepts the Measurement class object from the server and that the PlottableMeasurement object which the charts formerly used has been deprecated.
The styling props have been expanded, but if you need more, let me know.
(https://github.com/rcpch/digital-growth-charts-react-component-library/commit/4b79e348ac9047b29bf2da80b7abf1cab75f9969) closes this issue.

**Comment by BrianClevermed** [comment]
Thanks for the fast fix, I totally get not using object spread.

Just to note in the code such as `newStyle.infoBoxStroke == null || ''` is probably not what you want as `|| ''` will always be falsey as it is equivelant to `|| false` I think the code needs to be something like

`newStyle.infoBoxStroke = newStyle.infoBoxStroke == null || newStyle.infoBoxStroke == '' ? "#CDCDCD" : newStyle.infoBoxStroke`

or 

`newStyle.infoBoxStroke = newStyle.infoBoxStroke ? newStyle.infoBoxStroke : "#CDCDCD"`

the 2nd way is maybe a little less intuitive and could have some not intended behaviour if `newStyle.infoBoxStroke` is any [falsy value](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) then the check will "fail" and the default value will be used but I think in this case it is acceptable as any falsy value would not be what you want.

**Comment by eatyourpeas** [comment]
Thank you - it struck me that some of the values could simply be empty strings rather than null/undefined so added that in.
Testing for empty string though would be ```===`` though, not ```==```?

**Comment by BrianClevermed** [comment]
Ah yes you are correct it would be best to use `===`

`newStyle.infoBoxStroke = newStyle.infoBoxStroke == null || newStyle.infoBoxStroke === '' ? "#CDCDCD" : newStyle.infoBoxStroke`

**Comment by eatyourpeas** [comment]
Thanks that is helpful. I have been through and checked for null and length where the prop is a string. Pushing a patch now.
