### ISSUE TITLE
Pan/Zoom data points can be off screen

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-react-component-library#18]
It would be good to prevent panning where all the growth measurents are nolonger in the visible area of the chart.

**Comment by chvanlennep** [comment]
So this can be partly alleviated by setting the max domains on the victory chart to the domains as calculated by the getDomainsAndData function. This prevents zooming out too far.

I cannot see a way to properly prevent losing all visible points on zoom- victory manages the zooming state completely. The onZoomDomainChange is just a callback to link zoom state to an external state, there is no way to influence it as far as I can see.

**Comment by eatyourpeas** [comment]
Is it possible to to set domains plus or minus some padding around the plotted data x or y value onZoomDomainChange to prevent going off screen or would that send it up its arse?

**Comment by eatyourpeas** [comment]
By constraining the chart domains to the measurements this is in effect fixed. Thanks @chvanlennep .
