### ISSUE TITLE
The 'grey wedge' under the pubertal section should have clearer information

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-react-component-library#23]
![image](https://user-images.githubusercontent.com/2348385/128544034-87919bad-def2-41f4-966a-6b66b8adb2f4.png)

Can we link directly to the "instructions" that are mentioned? (presumably these come from the original paper chart cards)
Can we do this is a good-looking way? (ie can there be a little :information_source: type icon to click?)

Related: Is there therefore an argument for adding a "URL" field to the tooltip data (which comes from the **API** not the chart component) to enable adding a URL to any returned chart information?

**Comment by eatyourpeas** [comment]
This is fixed in the bone-ages branch.
