### ISSUE TITLE
Is it possible to set the age range displayed in the chart?

### ISSUE THREAD

**Issue by stephen775** [rcpch/digital-growth-charts-react-component-library#30]
Is it possible to set the age range displayed in the chart?

As if the child is say 5 years old it displays a 0-6 years range in the chart.

The clinicians would like the chart to be able to display a 0- 18 year range/even if the patient only 5 years old with observations up till that age.

Thanks
Stephen Plant

**Comment by eatyourpeas** [comment]
Thanks @stephen775 for posting this issue. Do you have any idea what the use case would be? The charts would look a bit odd if all the measurements are squashed up on the left hand side and towards the bottom. In theory it would be possible to increase the x and y domains of the charts to zoom all the way out but it would make the UI/UX quite complicated - it would probably mean another button at the foot of the chart which is starting to look quite busy now. The new version (see sds-branch) already has a cut/paste button to go with the others. The midparental centiles allow the user to see where the family sit for height so I am not clear what extra information this gives the user?

**Comment by eatyourpeas** [comment]
Transferring this issue to the chart repo.
This was discussed with Salford NHS Trust yesterday and was requested by their user group.
They felt it was helpful to zoom out to show the whole chart when discussing growth with families.
@stephen775 tagged to keep in the loop

### Implementation
Possible suggestion below
1. addition of a new toggle button at the foot of the chart which only renders when childMeasurement data has been passed to the charts.
2. would toggle the domains of the chart and the rendered lines between 20y (plus padding) and the existing constraints set when users enter childMeasurement data.
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1058647/164452489-8fa0d22e-79c8-40d5-a890-3bd1ebb2e008.png">

The first steps to implementation are in this [branch](https://github.com/rcpch/digital-growth-charts-react-component-library/tree/salford)

**Comment by eatyourpeas** [comment]
In follow up:
toggle now functioning:
constrained to measurements view:
![image](https://user-images.githubusercontent.com/1058647/164465460-dddcac25-3899-45df-bdc8-81bfeaa73c07.png)

full chart:
![image](https://user-images.githubusercontent.com/1058647/164465549-63c65a02-2116-4952-b8d4-83f954543c40.png)

Needs a bit more testing but hoping that is what your users are after @stephen775 ?

**Comment by stephen775** [comment]
Hi.
Yes it the ability to zoom out to show full 0 -20 years time line is what the were asking for.

So if you have a 10 year old with observations made 0 - 10years. They can zoom out to show parents the full 0 - 20 timeline with the 0 -1- actial observations.

**Comment by eatyourpeas** [comment]
I will merge this as a new version.
