### ISSUE TITLE
Show Gestational Age when hovering over pre-term measurements

### ISSUE THREAD

**Issue by snield1150** [rcpch/digital-growth-charts-react-component-library#37]
We have had a clinician point out that it would be helpful to see the 'gestational age' when hovering over a point on the chart for a pre-term baby (< 37 weeks). 
For example, DOB=10/01/23, Measurement Date = 10/01/23. Gestation = 36 weeks 0 day. The chart shows the 'adjusted' plot point as a cross and when you hover it says 'Corrected Age: undefined'. This was confusing to the clinician as they thought it was showing a 'corrected age'. Adding another measurement for same DOB and Measurement Date 28/02/23 does show 'Corrected Age: 3 weeks' which makes sense.
We have tested this in your Demo Chart site and it does the same, but unsure if this is by design.

**Comment by eatyourpeas** [comment]
Thanks for posting this. This relates to the chart component so moving this issue to that repository. This is something that we have noted and is on the worksheet to fix.

**Comment by eatyourpeas** [comment]
this has been fixed in https://github.com/rcpch/digital-growth-charts-react-component-library/commit/2508fc0618defbdab0335ec466d359c138cf72a4 and a new patch published to rpm
