### ISSUE TITLE
Initial setup of component returning sdsStroke undefined

### ISSUE THREAD

**Issue by JackCoops** [rcpch/digital-growth-charts-react-component-library#38]
Hi,

I've just set up the component and when trying to load it I get returned the error:
`Cannot read properties of undefined (reading 'sdsStroke')`

I've gotten around this by hardcoding the `sdsStroke` in the `centileStyle` but it is set to nullable in the typing so I thought I'd raise an issue.
```
<RCPCHChart
    centileStyle={{
       sdsStroke: '#A9A9A9',
     }}
    exportChartCallback={exportChartCallback}
    measurementMethod={measurementMethod}
    measurementsArray={measurementsArray}
    reference={reference}
    sex={sex}
    subtitle={subtitle}
    title={title}
/>
```

Thanks

**Comment by eatyourpeas** [comment]
Thanks @jcooperprioritydigitalhealth for this. There was a missing optional in the ```makeAllStyles.ts``` file where all the styles are initialised. I have pushed a patch.
