### ISSUE TITLE
mid_parental_height_centile returning undefined if midParentalHeightData prop isn't set in component

### ISSUE THREAD

**Issue by JackCoops** [rcpch/digital-growth-charts-react-component-library#39]
Not sure if it's a setup issue but I am finding that `mid_parental_height_centile` returns `undefined` unless midParentalHeightData is set to an empty array within the component call:

working example:
```
<RCPCHChart
     exportChartCallback={exportChartCallback}
     measurementMethod={measurementMethod}
     measurementsArray={measurementsArray}
     midParentalHeightData={{}}
     reference={reference}
     sex={sex}
     subtitle={subtitle}
     title={title}
/>
```

error occurs:
```
<RCPCHChart
     exportChartCallback={exportChartCallback}
     measurementMethod={measurementMethod}
     measurementsArray={measurementsArray}
     reference={reference}
     sex={sex}
     subtitle={subtitle}
     title={title}
/>
```

This is the error received:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/117279092/213181095-0f301d9c-3ca2-4792-90e7-6e1e792201cd.png">

**Comment by eatyourpeas** [comment]
Thanks for posting the issue. Having looked at this I can see that although the ```midParentalHeightData``` prop is optional, the CentileChart component was expecting an object. I have fixed this and pushed a patch. It should now be possible to omit the prop and still have functioning charts.

**Comment by pacharanero** [comment]
closed by @eatyourpeas
