### ISSUE TITLE
measurementFill property doesn't change Centile Chart point colour

### ISSUE THREAD

**Issue by dmc-cambric** [rcpch/digital-growth-charts-react-component-library#44]
Hi Team, 

Have noticed that specifying the measurementFill property on measurementStyle doesn't show the colour change for the chronological age or corrected age measurement points on the Centile chart.

Looking at the source code (src/CentileChart/CentileChart.tsx), it seems that the colour is hardcoded to black for corrected age measurement (Line 683) and that the measurementFill doesn't filter through to either the chronological age measurement point or the corrected age measurement point. 

Using version 6.1.4.

Thanks in advance, 
Daniel

**Comment by eatyourpeas** [comment]
Thanks @dmc-cambric for finding this - fix applied and new version pushed. Note latest charts now are 6.1.10
