### ISSUE TITLE
Toggle corrected and chronological ages

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-react-component-library#5]
Project board decided today to correct for gestation, even if term, across the life course. This means potentially plotting measurements for both ages, leading to a crowded chart. The solution was to render chronological age only if a toggle button is pressed.

**Comment by pacharanero** [comment]
We implemented this and actually when implemented it looked odd, we think possibly that having the X and O markers is good enough. There was also a question of which age should be rendered by default.

**Comment by eatyourpeas** [comment]
@statist7 issue opened on the server:
@eatyourpeas this afternoon seemed to be rowing back from the idea of providing a toggle to switch between unadjusted and adjusted age on the chart, on the grounds that it's not obvious which should be the default.

A solution would be to use the status quo, i.e. to default to

unadjusted age for term babies
adjusted age up to 1 year for preterm babies, and
adjusted age up to 2 years for very preterm babies.

**Comment by pacharanero** [comment]
That seems to be a quite sensible approach - it keeps us close to the expectations of current practice, while moving us forward in terms of capability to calculate GAC on all ages
