### ISSUE TITLE
Puberty region in height graphs blocked by grey box in Storybook

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#58]
On Storybook, when running the react-18-feature-test-branch, hovering below the puberty line elicits a filled box that pops up which blocks the screen. This happens between the precocious puberty line and post-17 completion delayed puberty.

Storybook CentileCharts affected: ‘With measurements from Birth Over Two Years’, ‘With Height and No Data’ (seems to be just the normal Height charts)

<img width="940" alt="image" src="https://github.com/rcpch/digital-growth-charts-react-component-library/assets/65614251/92d5ef68-8b22-4a43-a5d9-4ea2dce83a72">

**Comment by eatyourpeas** [comment]
thanks @dc2007git for seeing this. Do you have any more information about your set up? It should look like this:
<img width="828" alt="image" src="https://github.com/rcpch/digital-growth-charts-react-component-library/assets/1058647/11fb585e-4fd4-44a4-b8b4-6658a9d472aa">
Are there any errors in the console? Which browser are you using?

**Comment by dc2007git** [comment]
Hi @eatyourpeas, no worries. 

My setup is as follows:
- VScode v1.82.2
- Storybook v7.4.0
- Safari browser v16.5
- macOS Ventura 13.4

No errors in the console as far as I can see. Just a warning about Storybook's add-on:
CONSOLE OUTPUT: The "@storybook/addon-mdx-gfm" addon is meant as a migration assistant for Storybook 7.0; and will likely be removed in a future version.

Just tried again, same issue, both when hovering over the puberty region, and when outside of that shaded area but above 100cm Height/Length and between precocious puberty line and post-17 completion of puberty line. Once I start hovering on or above the 0.4th centile line, the box disappears.

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
