### ISSUE TITLE
Gradient-oriented labels bug

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#64]
On the centile charts, the labels of the centiles are loaded in at gradients at the respective points on the graph, however some gradients are broken. @eatyourpeas has already noticed this, just formalising it in an Issue.

Bugged gradient labels:
![image](https://github.com/rcpch/digital-growth-charts-react-component-library/assets/65614251/4a85ae4c-a269-460c-871f-5f571f3c8333)

Healthy gradient labels:
![image](https://github.com/rcpch/digital-growth-charts-react-component-library/assets/65614251/f6bd633a-24ee-4cda-8e3c-ab77ae920ff9)

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
