### ISSUE TITLE
chartScaleType defaults to biggerChild

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#66]
When a centile chart is rendered, the centile lines and axis are dependent on the parameter chartScaleType. This then informs the x-axis label, and whether months as lollipops will show up.

At the moment, every Storybook story (except 'With Premature Female Heights) is automatically rendering with the chartScaleType set to biggerChild, since this is the default. However, this means that the rendering of an appropriate x-label doesn't happen. For example, smallChild is defined as ≤ 4 years old, > 1 year old. But Storybook renders a child who has data plotted between 0-2 years on the biggerChild axis.

This has implications for rendering gradient labels as per Issue #64. If we can't use the chartScaleType as a conditional (because it always defaults to biggerChild), then the gradients can't be conditionally scaled up/down as appropriate and so will keep bugging out

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
