### ISSUE TITLE
Testing for dGC Component Library

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#70]
It looks like there isn't a testing suite automatically executed on the Component Library upon PR submission, like with Epilepsy12. 

For code safety reasons, this would be a good idea to implement and help ensure best CI/CD practices are being adhered to. Much like with Epilepsy12, it would also ensure that edge cases, dependency changes or any problems that would otherwise go missed are raised if adequate testing is in place.

At the moment Jest only has around ~20% code coverage for the component library, and while complete coverage shouldn't be our sole objective, we can afford to bump up the coverage numbers.

**Comment by eatyourpeas** [comment]
I second this. Jest has been included with Storybook in another branch with node bump and for next major release it seems to me we should include lots of tests.

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
