### ISSUE TITLE
No development branch?

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#71]
Looks like the component library doesn't have a development branch, like our other RCPCH projects. While not absolutely necessary, I think it would be good to have to standardise our workflows across projects. @pacharanero if you're happy to add it, we can branch off of the current live.

**Comment by pacharanero** [comment]
I have created a development branch and pushed this to `origin` - for consistency we should now generally make any non-trivial changes in `development` first then merge into `live` when ready.
