### ISSUE TITLE
Tooltips font loading Times New Roman locally

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#76]
Tooltips on growth charts should have Montserrat font, like in the live demo, but when running locally the font loads in as Times New Roman

**Comment by dc2007git** [comment]
To add context - this behaviour only seems to occur when using Storybook, so there is a good chance it's related to that. The live demo on rcpch.ac.uk works perfectly

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
