### ISSUE TITLE
Toggle ability to render gradient labels in graph

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#81]
Growth charts should have a toggle button, similar to that for the zoom functionality, which allows the user to choose whether they would like to display the Centile Labels in their view or not

**Comment by dc2007git** [comment]
This is being addressed in the branch `gradient-labels` and will be linked via PR

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
