### ISSUE TITLE
Refactor props for styles

### ISSUE THREAD

**Issue by dc2007git** [rcpch/digital-growth-charts-react-component-library#83]
[discussion on pairing session] Simon and I were having a discussion about styles. We spoke about the different styles, whether they are necessary, whether we should expose them to the user for customisation, and whether we should pass in only a theme prop as opposed to individual styles.

Points made:
- The title should not be exposed for customisation (to maintain the data label (ie UKWHO), and the chart type (ie height/length)). The SUBTITLE however, can be exposed, as the integrators may want to place patient information such as NHS number.

**Comment by eatyourpeas** [comment]
Fixed and merged in v7.0.0. Documentation updated
