### ISSUE TITLE
React buttons default to type submit and will submit html form

### ISSUE THREAD

**Issue by ryanlewis94** [rcpch/digital-growth-charts-react-component-library#88]
Our current implementation uses a form whereby users can submit patients details and save them by submitting a form.
I have noticed that when clicking any of the buttons on react component it will attempt to submit our form. I believe this is because in React if you do not specify a type, then the buttons default type is submit.
If possible can the buttons specify type button so we do not get this issue?

**Comment by mbarton** [comment]
Thanks for reporting @ryanlewis94 - I think this should be a straightforward change. Let me look into it

**Comment by mbarton** [comment]
Sorry for the delay on this one @ryanlewis94, we've now released a fix in v7.0.5:

- https://github.com/rcpch/digital-growth-charts-react-component-library/releases/tag/v7.0.5
- https://www.npmjs.com/package/@rcpch/digital-growth-charts-react-component-library/v/7.0.5

**Comment by ryanlewis94** [comment]
@mbarton it looks like gradient-labels-button does not specify a type and therefore is still causing the issue 
![image](https://github.com/user-attachments/assets/3a01f467-3816-43cd-9d70-bcb22b223e2c)

**Comment by mbarton** [comment]
Hmm yeah sorry about that - I thought I had covered off all the buttons. I'll have a look now

**Comment by mbarton** [comment]
@ryanlewis94 I've released v7.0.6 which fixes the gradient labels button too

- https://www.npmjs.com/package/@rcpch/digital-growth-charts-react-component-library/v/7.0.6
- https://github.com/rcpch/digital-growth-charts-react-component-library/releases/tag/v7.0.6
