### ISSUE TITLE
Implement deemphasised lines at nondisjunctions between references

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-react-component-library#98]
RCPCH Project Board 22.8.24

There has been longstanding confusion about the fact that centile lines between WHO and UK90 references do not line up. This is particularly seen in the head circumference chart where the overlap is of the order of 2 centiles. 

Decision was therefore made to implement de-emphasised vertical lines at the join between references, with a tooltip to explain the discrepancy to users.

Vertical lines (grey / deemphasised, no prop) for all measurement methods at:
- [x] aged 42 weeks
- [x] aged 4 years
- [x] vertical labels associated with each line explaining non-disjunction or retain existing tool tips.

**Comment by statist7** [comment]
Don't forget to include the disjunctions at 2 years for WHO height and BMI, due to the change from length to height.

**Comment by eatyourpeas** [comment]
Just to be clear - we always did have tool tips that appeared when users hovered over the breaks between references explaining the discrepancy and I have left those in. These extra lines are just clearer signposting. 
<img width="841" alt="image" src="https://github.com/user-attachments/assets/b8b2d35f-87d8-4d66-8c54-08863d1d5436">
especially for head circumference which initiated this issue.
<img width="886" alt="image" src="https://github.com/user-attachments/assets/9119a7b1-cfa7-4a1c-82a7-e7ccbb2aa715">
If @statist7 agrees (and everyone else) I will merge this in.
